### ISSUE TITLE
Item price not updated in cart

### ISSUE THREAD

**Issue by AymericJoubert** [Smile-SA/magento2-module-retailer-offer#1] opened 2016-08-12 15:37 UTC
The items already in cart don't take the new offer price when changing the retailer or the pickup date.

**Comment by romainruaud** [comment] 2016-08-16 09:43
Hello @AymericJoubert, I will need more informations about this issue since I am not able to reproduce it. Can you be more precise ? Thanks.

**Comment by romainruaud** [comment] 2016-08-17 11:24
Fixed on the retailer module. See https://github.com/Smile-SA/magento2-module-retailer/commit/9cd673cd4489b3a4b1e2520302434a4b68e032ff

**Closed by romainruaud** 2016-08-17 11:24 UTC
